/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DawgJni */

#ifndef _Included_DawgJni
#define _Included_DawgJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DawgJni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kentvu_dawgjava_DawgTrie_buildDawg
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
