/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DawgJni */

#ifndef _Included_DawgJni
#define _Included_DawgJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DawgJni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jlong JNICALL Java_kentvu_dawgjava_DawgTrie_dawgBuilder
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_kentvu_dawgjava_DawgTrie_dawgBuilderInsert
  (JNIEnv *, jobject, jlong, jstring);

JNIEXPORT void JNICALL Java_kentvu_dawgjava_DawgTrie_dawgBuilderFinish
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
