#include "HelloJNIImpl.h"

#include <memory>
#include <functional>
#include <iostream>

#include <jni.h>
#include "HelloWorld.h"   // auto-generated by `javah HelloJNI`


using std::string;
using std::function;
using std::unique_ptr;
using std::shared_ptr;
using std::cout;
using std::endl;


/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_sayHello
  (JNIEnv *env, jobject thisObj, jstring arg)
{
    DoSayHello(ToString(env, arg));

    //const string name = ToStringPtr(env, arg).get();
    //DoSayHello(name);
}


void DoSayHello(const string &name)
{
    cout << "Hello, " << name << endl;
}
