/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dawgswig;

public class DawgSwigMdlJNI {
  public final static native long new_DawgSwig();
  public final static native void delete_DawgSwig(long jarg1);
}
