/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package dawgswig;

public class DawgSwigMdlJNI {
  public final static native long new_DawgSwig(String jarg1);
  public final static native void DawgSwig_Insert(long jarg1, DawgSwig jarg1_, String jarg2);
  public final static native void DawgSwig_Finish(long jarg1, DawgSwig jarg1_);
  public final static native void delete_DawgSwig(long jarg1);
}
