name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache SWIG build
      id: cache-swig
      uses: actions/cache@v1
      with:
        path: swig/dist
        key: ${{ runner.os }}-swig

    - name: Checkout SWIG
      if: steps.cache-swig.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: swig/swig
        path: swig
    - name: Install SWIG from source
      if: steps.cache-swig.outputs.cache-hit != 'true'
      run: |
        ./build_swig.sh -d
    - name: Build with Gradle & SWIG
      run: |
        export PATH=$PWD/swig/dist/bin:$PATH
        ./gradlew --info build
    - name: Upload test reports
      continue-on-error: true
      uses: actions/upload-artifact@v1.0.0
      if: failure()
      with:
        name: test-result
        path: dawg-java/build/reports/tests/test/
    - name: Prepare SWIG artifacts
      continue-on-error: true
      run: |
        ./run_swig.sh prepare-artifacts artifacts/swig
    - name: Upload SWIG generated files
      uses: actions/upload-artifact@v1.0.0
      continue-on-error: true
      with:
        name: swig-generated
        path: artifacts/swig
    - name: Upload JNI lib
      uses: actions/upload-artifact@v1.0.0
      continue-on-error: true
      with:
        name: dawg-jni
        path: dawg-jni/build/lib/main/debug/

  android-test:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install swig
        run: brew install swig

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

