name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install SWIG
      run: |
        sudo apt-get -yqq install swig
    - name: Build with Gradle
      run: ./gradlew --info build
    - name: Upload test reports
      uses: actions/upload-artifact@v1.0.0
      if: failure()
      with:
        name: test-result
        path: dawg-java/build/reports/tests/test/
    - name: Upload SWIG artifacts
      uses: actions/upload-artifact@v1.0.0
      if: failure()
      with:
        name: swig-generated
        path: dawg-java/src/main/java/dawgswig
