name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout SWIG
      uses: actions/checkout@v2
      with:
        repository: swig/swig
        path: swig
        fetch-depth: 1
    - name: Install SWIG from source
      run: |
        sudo apt-get -yqq install automake bison
        cd swig
        ./autogen.sh
        ./configure --prefix=$PWD/dist
        make
        make install
    - name: Build with Gradle & SWIG
      run: |
        export PATH=$PWD/swig/dist/bin:$PATH
        ./gradlew --info build
    - name: Upload test reports
      uses: actions/upload-artifact@v1.0.0
      if: failure()
      with:
        name: test-result
        path: dawg-java/build/reports/tests/test/
    - name: Upload SWIG artifacts
      uses: actions/upload-artifact@v1.0.0
      if: failure()
      with:
        name: swig-generated
        path: dawg-java/src/main/java/dawgswig
