name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GPG_PASS: ${{ secrets.GPG_PASS }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle & SWIG
      run: |
        gpg --batch --yes --decrypt --passphrase="$GPG_PASS" \
          --output key.asc .github/key.asc.gpg
        echo signing.keyId=716EB882 >> gradle.properties
        echo signing.password="$SIGNING_PASSWORD" >> gradle.properties
        # PWD is ./dawg-java/
        echo signing.secretKeyRingFile=../key.asc >> gradle.properties
        ./gradlew --info clean build :dawg-java:publishGprPublicationToMavenLocal
        mkdir -pv repository/
        cp -rv ~/.m2/repository/kentvu repository || true
    - name: Upload test reports
      continue-on-error: true
      uses: actions/upload-artifact@v1.0.0
      if: failure()
      with:
        name: test-result
        path: dawg-java/build/reports/tests/test/
    - name: Prepare SWIG artifacts
      continue-on-error: true
      run: |
        ./run_swig.sh prepare-artifacts artifacts/swig
    - name: Upload SWIG generated files
      uses: actions/upload-artifact@v1.0.0
      continue-on-error: true
      with:
        name: swig-generated
        path: artifacts/swig
    - name: Upload lib artifact
      uses: actions/upload-artifact@v1.0.0
      continue-on-error: true
      with:
        name: dawg-java-jars
        path: repository/kentvu/dawgjava/dawg-java/
        #path: ${{ env.HOME }}/.m2/repository/kentvu/dawgjava/dawg-java/

  android-test:
    runs-on: macos-10.15 # macos-11.0 is not public for now
    steps:
      - name: checkout
        uses: actions/checkout@v2

        # SWIG already installed on Mac?
#      - name: install swig
#        run: brew install swig

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-build: 6110076
          script: ./gradlew clean :dawg-android:assemble connectedCheck

      - name: Persist test result
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dawg-android-test-result
          path: dawg-android/build/outputs/androidTest-results/connected

      - name: Upload lib artifact
        continue-on-error: true
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dawg-android
          path: dawg-android/build/outputs/aar
          # wildcard not supported /*-release.aar
